import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from 'react-router-dom';
import { Compass, Heart, ShoppingBag } from 'lucide-react';
const iconMap = {
    vet: _jsxs("svg", { xmlns: "http://www.w3.org/2000/svg", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2", strokeLinecap: "round", strokeLinejoin: "round", className: "w-10 h-10", children: [_jsx("path", { d: "M8 2v4M16 2v4M3 10h18M5 4h14a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2Z" }), _jsx("path", { d: "M12 14v4M10 16h4" })] }),
    park: _jsx("svg", { xmlns: "http://www.w3.org/2000/svg", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2", strokeLinecap: "round", strokeLinejoin: "round", className: "w-10 h-10", children: _jsx("path", { d: "M17 14h.01M7 7h.01M7 14h.01M12 14h.01M12 7h.01M17 7h.01M16 3H8a5 5 0 0 0-5 5v8a5 5 0 0 0 5 5h8a5 5 0 0 0 5-5V8a5 5 0 0 0-5-5Z" }) }),
    food: _jsx("svg", { xmlns: "http://www.w3.org/2000/svg", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2", strokeLinecap: "round", strokeLinejoin: "round", className: "w-10 h-10", children: _jsx("path", { d: "M18 8h1a4 4 0 0 1 0 8h-1M5 8h11v9a4 4 0 0 1-4 4H9a4 4 0 0 1-4-4V8ZM12 8V2" }) }),
    training: _jsxs("svg", { xmlns: "http://www.w3.org/2000/svg", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2", strokeLinecap: "round", strokeLinejoin: "round", className: "w-10 h-10", children: [_jsx("circle", { cx: "12", cy: "12", r: "10" }), _jsx("path", { d: "M12 8v4l3 3" })] }),
    grooming: _jsxs("svg", { xmlns: "http://www.w3.org/2000/svg", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2", strokeLinecap: "round", strokeLinejoin: "round", className: "w-10 h-10", children: [_jsx("path", { d: "M9 11a4 4 0 0 0 8 0" }), _jsx("path", { d: "m21 5-5 3 5 3M3 5l5 3-5 3" })] }),
    cafe: _jsxs("svg", { xmlns: "http://www.w3.org/2000/svg", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2", strokeLinecap: "round", strokeLinejoin: "round", className: "w-10 h-10", children: [_jsx("path", { d: "M17 8h1a4 4 0 1 1 0 8h-1M3 8h14v9a4 4 0 0 1-4 4H7a4 4 0 0 1-4-4Z" }), _jsx("line", { x1: "6", y1: "2", x2: "6", y2: "4" }), _jsx("line", { x1: "10", y1: "2", x2: "10", y2: "4" }), _jsx("line", { x1: "14", y1: "2", x2: "14", y2: "4" })] }),
    minders: _jsxs("svg", { xmlns: "http://www.w3.org/2000/svg", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2", strokeLinecap: "round", strokeLinejoin: "round", className: "w-10 h-10", children: [_jsx("path", { d: "M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" }), _jsx("circle", { cx: "9", cy: "7", r: "4" }), _jsx("path", { d: "M22 21v-2a4 4 0 0 0-3-3.87" }), _jsx("path", { d: "M16 3.13a4 4 0 0 1 0 7.75" })] }),
    advice: _jsxs("svg", { xmlns: "http://www.w3.org/2000/svg", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2", strokeLinecap: "round", strokeLinejoin: "round", className: "w-10 h-10", children: [_jsx("path", { d: "M9 18h6" }), _jsx("path", { d: "M10 22h4" }), _jsx("path", { d: "M12 2a7 7 0 0 0-4 12.9V17h8v-2.1A7 7 0 0 0 12 2z" })] })
};
const CategoryCard = ({ icon, title, link = '#' }) => {
    return (_jsxs(Link, { to: link, className: "flex flex-col items-center p-6 bg-white rounded-lg shadow-md hover:shadow-lg transition-shadow duration-300 border border-gray-100 hover:border-[#4A90E2]", children: [_jsx("div", { className: "mb-4 text-[#4A90E2]", children: iconMap[icon] }), _jsx("h3", { className: "text-lg font-semibold text-gray-800", children: title })] }));
};
const FeaturedCategories = () => {
    return (_jsx("section", { className: "py-16 bg-[#F8F4E3]", children: _jsxs("div", { className: "container mx-auto px-4", children: [_jsx("h2", { className: "text-3xl font-bold text-center mb-12 text-gray-800", children: "Explore Dog-Friendly Ireland" }), _jsxs("div", { className: "grid grid-cols-2 md:grid-cols-3 lg:grid-cols-8 gap-6", children: [_jsx(CategoryCard, { icon: "vet", title: "Find a Vet", link: "/vets" }), _jsx(CategoryCard, { icon: "park", title: "Parks & Walks", link: "/parks" }), _jsx(CategoryCard, { icon: "food", title: "Nutrition", link: "/nutrition" }), _jsx(CategoryCard, { icon: "training", title: "Dog Training", link: "/training" }), _jsx(CategoryCard, { icon: "grooming", title: "Grooming", link: "/grooming" }), _jsx(CategoryCard, { icon: "cafe", title: "Dog-Friendly Places", link: "/places" }), _jsx(CategoryCard, { icon: "minders", title: "Find Dog Minders", link: "/minders" }), _jsx(CategoryCard, { icon: "advice", title: "Advice from chat bot", link: "/advice" })] }), _jsx("div", { className: "mt-12 flex justify-center", children: _jsxs("div", { className: "flex space-x-8", children: [_jsxs("div", { className: "flex items-center", children: [_jsx(Compass, { className: "w-6 h-6 text-[#4A90E2] mr-2" }), _jsx("span", { className: "text-gray-700", children: "Find Services" })] }), _jsxs("div", { className: "flex items-center", children: [_jsx(Heart, { className: "w-6 h-6 text-[#4A90E2] mr-2" }), _jsx("span", { className: "text-gray-700", children: "Save Favorites" })] }), _jsxs("div", { className: "flex items-center", children: [_jsx(ShoppingBag, { className: "w-6 h-6 text-[#4A90E2] mr-2" }), _jsx("span", { className: "text-gray-700", children: "Community Marketplace" })] })] }) })] }) }));
};
export default FeaturedCategories;
